<?php

namespace Database\Seeders;

use App\Models\Project;
use App\Models\Unit;
use App\Models\User;
use Illuminate\Database\Seeder;

class UnitSeeder extends Seeder
{
    public function run(): void
    {
        $founder = User::where('role', 'founder')->first() ?? User::first();
        $createdById = $founder?->id;

        $unitsData = [
            // =========================================================================
            // Project 1: Grand Kavling Harmoni Asri (Standard: 100m2, Excess/m2: 1.5jt, Base: 150jt)
            // =========================================================================
            [
                'id' => 1,
                'project_id' => 1,
                'code' => 'A-01',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 150000000.00,
                'final_selling_price' => 185000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 2,
                'project_id' => 1,
                'code' => 'A-02',
                'category' => 'kavling',
                'type' => 'Kavling Hook',
                'land_width' => 9.00,
                'land_length' => 15.00,
                'land_area' => 135.00,
                'excess_land_area' => 35.00,
                'excess_cost' => 52500000.00,
                'hpp' => 202500000.00,
                'final_selling_price' => 245000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 3,
                'project_id' => 1,
                'code' => 'A-03',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 150000000.00,
                'final_selling_price' => 180000000.00,
                'status' => 'disetujui',
                'created_by' => $createdById,
            ],
            [
                'id' => 4,
                'project_id' => 1,
                'code' => 'A-04',
                'category' => 'kavling',
                'type' => 'Kavling Kelebihan',
                'land_width' => 10.00,
                'land_length' => 12.00,
                'land_area' => 120.00,
                'excess_land_area' => 20.00,
                'excess_cost' => 30000000.00,
                'hpp' => 180000000.00,
                'final_selling_price' => null,
                'status' => 'menunggu_persetujuan',
                'created_by' => $createdById,
            ],
            [
                'id' => 5,
                'project_id' => 1,
                'code' => 'A-05',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 150000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 6,
                'project_id' => 1,
                'code' => 'A-06',
                'category' => 'rumah',
                'type' => 'Rumah Type 45/100',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'building_area' => 45.00,
                'floors_count' => 1,
                'specifications' => 'Pondasi batu kali, struktur beton bertulang, dinding bata merah diplester, lantai granit 60x60, atap baja ringan & genteng beton, listrik 1300W, air sumur bor.',
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 280000000.00,
                'final_selling_price' => 330000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 7,
                'project_id' => 1,
                'code' => 'A-07',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 150000000.00,
                'final_selling_price' => null,
                'status' => 'ditolak',
                'created_by' => $createdById,
            ],
            [
                'id' => 8,
                'project_id' => 1,
                'code' => 'A-08',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 150000000.00,
                'final_selling_price' => null,
                'status' => 'draft',
                'created_by' => $createdById,
            ],
            [
                'id' => 20,
                'project_id' => 1,
                'code' => 'A-09',
                'category' => 'kavling',
                'type' => 'Kavling Hook',
                'land_width' => 11.00,
                'land_length' => 12.00,
                'land_area' => 132.00,
                'excess_land_area' => 32.00,
                'excess_cost' => 48000000.00,
                'hpp' => 198000000.00,
                'final_selling_price' => null,
                'status' => 'booked',
                'created_by' => $createdById,
            ],
            [
                'id' => 21,
                'project_id' => 1,
                'code' => 'A-10',
                'category' => 'rumah',
                'type' => 'Rumah Type 54/110',
                'land_width' => 10.00,
                'land_length' => 11.00,
                'land_area' => 110.00,
                'building_area' => 54.00,
                'floors_count' => 1,
                'specifications' => '3 Kamar Tidur, 2 Kamar Mandi, Carport 2 Mobil, Granit 60x60, Kusen Alumunium, Listrik 2200W.',
                'excess_land_area' => 10.00,
                'excess_cost' => 15000000.00,
                'hpp' => 310000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 22,
                'project_id' => 1,
                'code' => 'A-11',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 150000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 23,
                'project_id' => 1,
                'code' => 'A-12',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 150000000.00,
                'final_selling_price' => null,
                'status' => 'batal',
                'created_by' => $createdById,
            ],

            // =========================================================================
            // Project 2: Kavling Cluster Permata Hijau (Standard: 90m2, Excess/m2: 1.2jt, Base: 120jt)
            // =========================================================================
            [
                'id' => 9,
                'project_id' => 2,
                'code' => 'B-01',
                'category' => 'rumah',
                'type' => 'Rumah Type 36/90',
                'land_width' => 9.00,
                'land_length' => 10.00,
                'land_area' => 90.00,
                'building_area' => 36.00,
                'floors_count' => 1,
                'specifications' => '2 Kamar Tidur, 1 Kamar Mandi, Dapur Minimalis, Keramik 50x50, Atap Baja Ringan, Listrik 1300W.',
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 240000000.00,
                'final_selling_price' => 290000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 10,
                'project_id' => 2,
                'code' => 'B-02',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 9.00,
                'land_length' => 10.00,
                'land_area' => 90.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 120000000.00,
                'final_selling_price' => 145000000.00,
                'status' => 'disetujui',
                'created_by' => $createdById,
            ],
            [
                'id' => 11,
                'project_id' => 2,
                'code' => 'B-03',
                'category' => 'kavling',
                'type' => 'Kavling Hook',
                'land_width' => 10.00,
                'land_length' => 11.00,
                'land_area' => 110.00,
                'excess_land_area' => 20.00,
                'excess_cost' => 24000000.00,
                'hpp' => 144000000.00,
                'final_selling_price' => null,
                'status' => 'menunggu_persetujuan',
                'created_by' => $createdById,
            ],
            [
                'id' => 12,
                'project_id' => 2,
                'code' => 'B-04',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 9.00,
                'land_length' => 10.00,
                'land_area' => 90.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 120000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 13,
                'project_id' => 2,
                'code' => 'B-05',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 9.00,
                'land_length' => 10.00,
                'land_area' => 90.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 120000000.00,
                'final_selling_price' => null,
                'status' => 'batal',
                'created_by' => $createdById,
            ],
            [
                'id' => 24,
                'project_id' => 2,
                'code' => 'B-06',
                'category' => 'rumah',
                'type' => 'Rumah Type 45/95',
                'land_width' => 9.50,
                'land_length' => 10.00,
                'land_area' => 95.00,
                'building_area' => 45.00,
                'floors_count' => 1,
                'specifications' => 'Pondasi cakar ayam, dinding bata ringan, lantai granit 60x60, closet duduk Toto, listrik 1300W.',
                'excess_land_area' => 5.00,
                'excess_cost' => 6000000.00,
                'hpp' => 260000000.00,
                'final_selling_price' => 310000000.00,
                'status' => 'disetujui',
                'created_by' => $createdById,
            ],
            [
                'id' => 25,
                'project_id' => 2,
                'code' => 'B-07',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 9.00,
                'land_length' => 10.00,
                'land_area' => 90.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 120000000.00,
                'final_selling_price' => null,
                'status' => 'booked',
                'created_by' => $createdById,
            ],
            [
                'id' => 26,
                'project_id' => 2,
                'code' => 'B-08',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 9.00,
                'land_length' => 10.00,
                'land_area' => 90.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 120000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 27,
                'project_id' => 2,
                'code' => 'B-09',
                'category' => 'kavling',
                'type' => 'Kavling Kelebihan',
                'land_width' => 9.00,
                'land_length' => 12.00,
                'land_area' => 108.00,
                'excess_land_area' => 18.00,
                'excess_cost' => 21600000.00,
                'hpp' => 141600000.00,
                'final_selling_price' => 170000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 28,
                'project_id' => 2,
                'code' => 'B-10',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 9.00,
                'land_length' => 10.00,
                'land_area' => 90.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 120000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],

            // =========================================================================
            // Project 3: Griya Asri Residence (Standard: 120m2, Excess/m2: 1jt, Base: 180jt)
            // =========================================================================
            [
                'id' => 14,
                'project_id' => 3,
                'code' => 'C-01',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 12.00,
                'land_area' => 120.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 180000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 15,
                'project_id' => 3,
                'code' => 'C-02',
                'category' => 'kavling',
                'type' => 'Kavling Hook',
                'land_width' => 12.00,
                'land_length' => 12.00,
                'land_area' => 144.00,
                'excess_land_area' => 24.00,
                'excess_cost' => 24000000.00,
                'hpp' => 204000000.00,
                'final_selling_price' => 240000000.00,
                'status' => 'disetujui',
                'created_by' => $createdById,
            ],
            [
                'id' => 16,
                'project_id' => 3,
                'code' => 'C-03',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 12.00,
                'land_area' => 120.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 180000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 17,
                'project_id' => 3,
                'code' => 'C-04',
                'category' => 'rumah',
                'type' => 'Rumah Type 54/120',
                'land_width' => 10.00,
                'land_length' => 12.00,
                'land_area' => 120.00,
                'building_area' => 54.00,
                'floors_count' => 1,
                'specifications' => '3 Kamar Tidur, 2 Kamar Mandi, Ruang Tamu Luas, Dapur Granit, Listrik 2200W, Air PDAM.',
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 320000000.00,
                'final_selling_price' => null,
                'status' => 'menunggu_persetujuan',
                'created_by' => $createdById,
            ],
            [
                'id' => 29,
                'project_id' => 3,
                'code' => 'C-05',
                'category' => 'rumah',
                'type' => 'Rumah Type 70/140 (2 Lantai)',
                'land_width' => 10.00,
                'land_length' => 14.00,
                'land_area' => 140.00,
                'building_area' => 70.00,
                'floors_count' => 2,
                'specifications' => 'Desain Tropis Modern 2 Lantai, 4 Kamar Tidur, 3 Kamar Mandi, Balkon, Carport 2 Mobil, Smart Door Lock.',
                'excess_land_area' => 20.00,
                'excess_cost' => 20000000.00,
                'hpp' => 450000000.00,
                'final_selling_price' => 540000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 30,
                'project_id' => 3,
                'code' => 'C-06',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 12.00,
                'land_area' => 120.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 180000000.00,
                'final_selling_price' => null,
                'status' => 'booked',
                'created_by' => $createdById,
            ],
            [
                'id' => 31,
                'project_id' => 3,
                'code' => 'C-07',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 10.00,
                'land_length' => 12.00,
                'land_area' => 120.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 180000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 32,
                'project_id' => 3,
                'code' => 'C-08',
                'category' => 'kavling',
                'type' => 'Kavling Hook',
                'land_width' => 11.00,
                'land_length' => 14.00,
                'land_area' => 154.00,
                'excess_land_area' => 34.00,
                'excess_cost' => 34000000.00,
                'hpp' => 214000000.00,
                'final_selling_price' => 255000000.00,
                'status' => 'disetujui',
                'created_by' => $createdById,
            ],

            // =========================================================================
            // Project 4: Kavling Graha Perdana (Standard: 80m2, Excess/m2: 800rb, Base: 95jt)
            // =========================================================================
            [
                'id' => 18,
                'project_id' => 4,
                'code' => 'D-01',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 8.00,
                'land_length' => 10.00,
                'land_area' => 80.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 95000000.00,
                'final_selling_price' => 115000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 19,
                'project_id' => 4,
                'code' => 'D-02',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 8.00,
                'land_length' => 10.00,
                'land_area' => 80.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 95000000.00,
                'final_selling_price' => 115000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 33,
                'project_id' => 4,
                'code' => 'D-03',
                'category' => 'kavling',
                'type' => 'Kavling Standar',
                'land_width' => 8.00,
                'land_length' => 10.00,
                'land_area' => 80.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 95000000.00,
                'final_selling_price' => 115000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 34,
                'project_id' => 4,
                'code' => 'D-04',
                'category' => 'kavling',
                'type' => 'Kavling Hook',
                'land_width' => 10.00,
                'land_length' => 10.00,
                'land_area' => 100.00,
                'excess_land_area' => 20.00,
                'excess_cost' => 16000000.00,
                'hpp' => 111000000.00,
                'final_selling_price' => 135000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 35,
                'project_id' => 4,
                'code' => 'D-05',
                'category' => 'rumah',
                'type' => 'Rumah Type 36/80',
                'land_width' => 8.00,
                'land_length' => 10.00,
                'land_area' => 80.00,
                'building_area' => 36.00,
                'floors_count' => 1,
                'specifications' => '2 Kamar Tidur, 1 Kamar Mandi, Keramik 40x40, Atap Galvalum, Listrik 1300W, Sumur Gali.',
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 175000000.00,
                'final_selling_price' => 210000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],

            // =========================================================================
            // Project 5: Cluster Mutiara Malioboro (Standard: 150m2, Excess/m2: 2.5jt, Base: 350jt)
            // =========================================================================
            [
                'id' => 36,
                'project_id' => 5,
                'code' => 'E-01',
                'category' => 'rumah',
                'type' => 'Rumah Mewah Type 90/150 (2 Lantai)',
                'land_width' => 10.00,
                'land_length' => 15.00,
                'land_area' => 150.00,
                'building_area' => 90.00,
                'floors_count' => 2,
                'specifications' => '4 Kamar Utama, 3 Kamar Mandi En-suite, Lantai Marble / Granit Premium, Kitchen Set, Water Heater, Listrik 3500W.',
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 650000000.00,
                'final_selling_price' => 820000000.00,
                'status' => 'terjual',
                'created_by' => $createdById,
            ],
            [
                'id' => 37,
                'project_id' => 5,
                'code' => 'E-02',
                'category' => 'kavling',
                'type' => 'Kavling Prime Hook',
                'land_width' => 12.00,
                'land_length' => 15.00,
                'land_area' => 180.00,
                'excess_land_area' => 30.00,
                'excess_cost' => 75000000.00,
                'hpp' => 425000000.00,
                'final_selling_price' => 520000000.00,
                'status' => 'disetujui',
                'created_by' => $createdById,
            ],
            [
                'id' => 38,
                'project_id' => 5,
                'code' => 'E-03',
                'category' => 'kavling',
                'type' => 'Kavling Prime Standar',
                'land_width' => 10.00,
                'land_length' => 15.00,
                'land_area' => 150.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 350000000.00,
                'final_selling_price' => null,
                'status' => 'menunggu_persetujuan',
                'created_by' => $createdById,
            ],
            [
                'id' => 39,
                'project_id' => 5,
                'code' => 'E-04',
                'category' => 'kavling',
                'type' => 'Kavling Prime Standar',
                'land_width' => 10.00,
                'land_length' => 15.00,
                'land_area' => 150.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 350000000.00,
                'final_selling_price' => null,
                'status' => 'booked',
                'created_by' => $createdById,
            ],
            [
                'id' => 40,
                'project_id' => 5,
                'code' => 'E-05',
                'category' => 'kavling',
                'type' => 'Kavling Prime Standar',
                'land_width' => 10.00,
                'land_length' => 15.00,
                'land_area' => 150.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 350000000.00,
                'final_selling_price' => null,
                'status' => 'tersedia',
                'created_by' => $createdById,
            ],
            [
                'id' => 41,
                'project_id' => 5,
                'code' => 'E-06',
                'category' => 'kavling',
                'type' => 'Kavling Prime Standar',
                'land_width' => 10.00,
                'land_length' => 15.00,
                'land_area' => 150.00,
                'excess_land_area' => 0.00,
                'excess_cost' => 0.00,
                'hpp' => 350000000.00,
                'final_selling_price' => null,
                'status' => 'draft',
                'created_by' => $createdById,
            ],
        ];

        foreach ($unitsData as $unitData) {
            Unit::updateOrCreate(['id' => $unitData['id']], $unitData);
        }
    }
}
